repos:
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.2.0
  #   hooks:
  #     - id: interrogate
  #       exclude: ^(docs|setup.py|tests)
  #       args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespaces
        description: Trailing whitespaces are trimmed
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
        name: End of File Fix
        description: Checks file ends on newline
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: file-contents-sorter
        files: requirements-dev.txt
      - id: check-added-large-files
        args: ['--maxkb=300']

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
    # Enforce that notebooks outputs are cleared
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        args:
          [
            --max-size=1k
          ]

  #   # Docformatter to format docstrings
  # - repo: https://github.com/PyCQA/docformatter
  #   rev: v1.7.5
  #   hooks:
  #     - id: docformatter
  #       additional_dependencies: [tomli]
  #       args: [--config=./pyproject.toml]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

    # Use black to clean code in python and jupyter notebook cells
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
      - id: black-jupyter
        language_version: python3
        args: [--config=./pyproject.toml]

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #   -   id: flake8

  # # Check on large files as last hook
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.4.0
  #   hooks:
  #     - id: check-added-large-files
  #       args: ['--maxkb=300']

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.770
  #   hooks:
  #     - id: mypy
  #       exclude: docs/source/conf.py
  #       args: [--ignore-missing-imports]

  # # check for code spelling
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.4
  #   hooks:
  #   - id: codespell
  #     additional_dependencies: [tomli]
  #     args: [--toml=./pyproject.toml]
