name: sdm_eurec4a_docs
channels:
  - defaults
dependencies:
  - python = 3.12
  - pip >= 23.3.2
  - pytest >= 7.4.4
  - sphinx >= 7.2.6
  # Further dependencies
  - numpy >= 1.26.3
  - scipy >= 1.11.4
  - pandas >= 2.1.4
  - lmfit >= 1.2.2
  - matplotlib >= 3.8.2
  - cftime >= 1.6.3
  - cartopy >= 0.22.0
  - click >= 8.1.7
  - pre-commit >= 3.6.0
  - bottleneck >= 1.3.5
  - netcdf4 >= 1.6.5
  - dask >= 2023.12.1
  - xarray >= 2023.12.0
  # Further dependencies for the analysis
  - pip:
    - pyshp >= 2.3.1 # necessary for cartopy to work on HPC (https://github.com/SciTools/cartopy/issues/2284)
    - sphinx-book-theme
    - myst_parser
    # If fails, also install the package itself
    - "git+https://github.com/nilsnevertree/sdm-eurec4a.git"
