name: pre-commit

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v5.5.0
      with:
        python-version: "3.12"

    - name: Pre-commit run
      uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
      with:
        msg: apply code formatting
      # with:
      #   extra_args: run --all-files
